# Generated by Django 5.1.4 on 2025-04-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
